### PR TITLE
Add support for building the library as an external module

### PR DESCRIPTION
**Pull request by nxrighthere**
Thank you for the library, Doug, it works great.

### CODE REVIEW

**Comment by nxrighthere** [comment]
@dougbinks Doug, I really like your task scheduler, so I just made a [C# wrapper](https://github.com/nxrighthere/EnkiTasks-CSharp) in order to use it in .NET. 👍

**Comment by dougbinks** [comment]
Glad you like the scheduler - I'm not able to look into the pull request right now but will do so asap!

**Comment by dougbinks** [comment]
I've just pushed a new branch master-sharedlib with some modifications. If possible could you check this works for you and if so I'll merge to master.

https://github.com/dougbinks/enkiTS/tree/master-sharedlib

**Comment by nxrighthere** [comment]
Yep, it works like a charm. 👌 

Maybe it makes sense to add an option for `/MT` / `-static`, so all required dependencies will be composed into a single library.

**Comment by dougbinks** [comment]
Many thanks for this, I've updated the readme with a link now as well.

**Comment by nxrighthere** [comment]
Thanks. 👍

**Pull request merged**
