### PR TITLE
Install headers in a subdirectory

### PR DESCRIPTION
**Pull request by bkmgit**
Solves https://github.com/dougbinks/enkiTS/issues/108

### CODE REVIEW

**Comment by pr0g** [comment]
Hey there,

I took a look at this and it totally makes sense, but I think it would technically constitute a breaking change (if anyone was depending on how the library is installed right now). So maybe a version bump if that's possible would be a good idea?

I intentionally didn't add the library name folder to keep things the same as when including files via `FetchContent`, as the folder name isn't there in that case. With this change I believe the include paths would be different if using `FetchContent` of `find_package` via installing. It's not a huge deal but probably worth mentioning somewhere in the docs too for usage (when I install I usually use a local folder via `CMAKE_INSTALL_PREFIX` so hadn't run into this issue before).

So this can be merged but I'd recommend maybe a small doc update if possible and a version bump to indicate the change. Maybe that's overkill, but just a suggestion. This is up to @dougbinks.

Thanks!

**Comment by pr0g** [comment]
Updates look great thanks @bkmgit 👍 For the docs I reckon the [Building](https://github.com/dougbinks/enkiTS#building) section of the README is as good a place as any. If it isn't too much trouble it would also be great to check this repo works with your changes (I believe it should) - https://github.com/pr0g/enkiTS-example. You just need to update the `CMakeLists.txt` file in the `third-party` folder to your repo (see [here](https://github.com/pr0g/enkiTS-example/blob/cmake-install-example/third-party/CMakeLists.txt). Cheers!

**Comment by dougbinks** [comment]
Thanks for this work both of you!

I'm happy to merge this without the documentation, and have the documentation added in another PR. I'll perform a few more checks and merge soon.

I intend to tag a new version soon once this is done.

**Comment by pr0g** [comment]
Sounds great @dougbinks 🙌 Thanks!

**Comment by bkmgit** [comment]
Thanks. Will do a few more checks and add a pull request with
documentation tomorrow. Can you postpone making a new release until Monday?

**Comment by dougbinks** [comment]
Please take your time, there's no rush and I'll wait for your PR before making a new release.

I may merge this PR to the dev branch in the meantime.

**Pull request merged**
