### PR TITLE
Add soname to shared library

### PR DESCRIPTION
**Pull request by bkmgit**
Fixes https://github.com/dougbinks/enkiTS/issues/107

### CODE REVIEW

**Comment by dougbinks** [comment]
Once again thanks for the issue #107 and this PR.

I have tested the PR on a variety of platforms and it works, though the versioning information is not set on the Windows DLL (using versioned DLLs on Windows is complex so I'm don't see this as an issue).

I'm going to consider this a bit more before deciding whether to merge, as it means I have to maintain the version number in the `cmakelists.txt` file.

**Comment by bkmgit** [comment]
Thanks. It is possible to pull the version number from Git history
whenever a new tag is made. Can update it to do that, if it will make
maintenance easier, though would make the review a little more complicated.

**Comment by bkmgit** [comment]
`git describe` will get version information.  Can add a GitHub action that would update the CMakeLists.txt file or a plain text  VERSION file when needed. If a plain text VERSION file is used, CMake can read the version number from this.

**Comment by dougbinks** [comment]
That sounds like a good idea. I'll have a go at doing that.

**Pull request merged**
