### PR TITLE
Make file formatting comply with POSIX standards

### PR DESCRIPTION
**Pull request by aaronfranke**
The POSIX standard for text files says that each text file should end with a newline, otherwise it is by definition not a text file. GitHub shows a warning when a file is committed without a terminating newline (see the "before" diffs of this PR), and GCC shows warnings when compiling files that don't end with newlines. See [this SO question](https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline/25322168) and [this Unix SE question](https://unix.stackexchange.com/questions/18743/whats-the-point-in-adding-a-new-line-to-the-end-of-a-file) for more information.

### CODE REVIEW

**Comment by dougbinks** [comment]
I cannot reproduce a warning from GCC - how are you compiling the code to get a warning?

**Comment by aaronfranke** [comment]
I'm not getting a warning myself specifically since I haven't tried compiling, but it's [a known issue](https://stackoverflow.com/questions/72271/no-newline-at-end-of-file-compiler-warning).

Actually, from the link it appears to only be an issue if you target C++ versions before C++11, but it's still a good idea to fix this even if you only target newer C++ versions.

**Comment by aaronfranke** [comment]
@dougbinks Any update?

I should probably explain why I made this PR, it's because I would like to enforce proper file formatting in downstream projects that use this library. Upstreaming these changes would be nice.

**Comment by dougbinks** [comment]
Your reasoning here is circular - you want to enforce this file formatting because you want to enforce this file formatting.

As you've already noted you've not experienced any issues related to this, and this formatting is likely to get frequently broken when changes are made.

Reading back on your comments I note: "specifically since I haven't tried compiling" - how did you test your PR if you didn't compile the code?

**Comment by aaronfranke** [comment]
I didn't test it, because this change never breaks anything.

It's not circular logic. I want to enforce file formatting on my downstream projects for consistency between my files. I want to enforce file formatting in this repo because I'm doing it in downstream repos.

**Comment by dougbinks** [comment]
> I didn't test it, because this change never breaks anything.
All code changes must be tested, which at minimum means compiling and running the samples and tests.

> ensure it works properly with my tools
Let me know which tool it causes issues with. However I am confused since you're not compiling the code.

> I want to enforce file formatting in this repo because I'm doing it in downstream repos.
This is what I mean by circular logic - you want to enforce this because you want to enforce this.

My current plan with this PR is to wait until I have further changes which need integrating, so that I can combine the testing and change process together so I loose less time in the process.

**Pull request merged**
